package pl.bartelomelo.stalcraftpda.util

val medicineInventory = mapOf(
    "0rdld.json" to "3rd Class ThermoBlock",
    "1r2l6.json" to "Astrixin",
    "1r2o6.json" to "Scientific First-Aid Kit",
    "3g1qz.json" to "Vodka",
    "4qgop.json" to "3rd Class Antirad",
    "5lzyg.json" to "Vinca",
    "6w59j.json" to "STRIKE",
    "7ly13.json" to "Guide’s First-Aid Kit",
    "96430.json" to "Personal First-Aid Kit",
    "dmky5.json" to "ClearMind+",
    "g4l10.json" to "ATLAS Anabolic Steroid",
    "g4lk0.json" to "Army First-Aid Kit",
    "j5mn7.json" to "2nd Class ThermoBlock",
    "j5mq7.json" to "1st Class Antidote",
    "kno60.json" to "2nd Class Psy-Blocker",
    "lynkj.json" to "Jiden EXTRA Energy Drink",
    "lynrj.json" to "3rd Class Antidote",
    "m0pqj.json" to "1st Class Psy-Blocker",
    "p62q6.json" to "Morphine",
    "qj9q6.json" to "3rd Class Psy-Blocker",
    "qj9y6.json" to "2nd Class Antidote",
    "rw1mg.json" to "Hercules",
    "rw1vg.json" to "1st Class ThermoBlock",
    "vjy3n.json" to "Epinephrine",
    "wjw9p.json" to "2nd Class Antirad",
    "y3kgz.json" to "1st Class Antirad",
    "zzqk2.json" to "Bandage"
)

val bulletInventory = mapOf(
    "0o01.json" to "Gauss Rifle Charger",
    "0or1.json" to "12 Caliber Slug",
    "1n91.json" to "7.62 mm Round",
    "1nr1.json" to "9 mm Armor-piercing Round",
    "2p16.json" to "5.56 mm Armor-Piercing Round",
    "2pr6.json" to "Tank of Combustible Mixture",
    "3v4g.json" to "5.56 mm Expanding Round",
    "3vog.json" to "12.7x55 Round",
    "4dkn.json" to "9x39 mm SP-6 Round",
    "5250.json" to "7.62 mm Incendiary Round",
    "52l0.json" to "9 mm SBP Round",
    "63oy.json" to "5.56 SBP Round",
    "63yy.json" to "12.7x55 mm Sniper Round",
    "7977.json" to "5.56 mm Incendiary Round",
    "79w7.json" to "12.7x55 AP Round",
    "9g6z.json" to "9 mm Round",
    "d1mn.json" to "5.56 mm Round",
    "g54p.json" to "9 mm Expanding Round",
    "g5np.json" to "7.62 mm Armor-Piercing Round",
    "j456.json" to "12 Caliber Buckshot",
    "kkrv.json" to "9x39 mm BP Round",
    "l601.json" to "7.62 mm Sniper Round",
    "l6y1.json" to "12 Caliber Birdshot",
    "mj07.json" to "5.45 mm Round",
    "nl43.json" to "5.45 mm Expanding Round",
    "nlk3.json" to "10 mm Round",
    "ork0.json" to "5.45 mm Armor-Piercing Round",
    "p062.json" to "5.45 mm Incendiary Round",
    "p0j2.json" to "10 mm Incendiary Round",
    "qm0k.json" to "Large-Caliber Handmade Round",
    "qmjk.json" to "12 Caliber Incendiary",
    "row5.json" to "12 Caliber Hunting Round",
    "vdjd.json" to "5.45 mm SBP Round",
    "vdnd.json" to "Tank of Combustible Mixture",
    "w23o.json" to "9x39 mm SP-5 Round",
    "y94o.json" to "7.62 mm SBP Round",
    "z13n.json" to "7.62 mm Expanding Round",
    "z1zn.json" to "9 mm Incendiary Round",
)

val weaponInventory = mapOf(
    "assault_rifle" to "Assault rifle",
    "device" to "Device",
    "heavy" to "Heavy",
    "machine_gun" to "Machine gun",
    "melee" to "Melee",
    "pistol" to "Pistol",
    "shotgun_rifle" to "Shotgun rifle",
    "sniper_rifle" to "Sniper rifle",
    "submachine_gun" to "Submachine gun"
)

val assultRiffleInventory = mapOf(
    "0r2zd.json" to "Balance",
    "0r3nd.json" to "Worn HK G3A1",
    "1r731.json" to "Kbk wz. 88 Tantal",
    "1rd56.json" to "AKS-74",
    "2odq0.json" to "АК-203",
    "3gn5g.json" to "TKB-0146M",
    "3gr6z.json" to "M4A1 CQC",
    "4q09p.json" to "HK G3A1",
    "5ld1g.json" to "OTs-14 Groza",
    "5ldkg.json" to "AKM",
    "5ldwg.json" to "AKS-74U",
    "6wr5j.json" to "АК-15",
    "7lnj7.json" to "SA-58 CTC",
    "7lry3.json" to "AMB-17",
    "7lrz3.json" to "AK-103",
    "96my0.json" to "ALK-22 Dragonfly",
    "dmqg5.json" to "AKM Tishina",
    "dmqk5.json" to "АМ-17",
    "g4060.json" to "L85A1",
    "j5l37.json" to "AEK-971",
    "j5l77.json" to "Worn L85A1",
    "j5lk7.json" to "M16A3",
    "j5od6.json" to "FAMAS G2",
    "knl30.json" to "FN F2000 Tactical",
    "knl70.json" to "Cleaner’s AKS",
    "lyl3j.json" to "ASh-12",
    "lyl7j.json" to "M16A1",
    "lyljj.json" to "M4 LB",
    "m023j.json" to "Worn SIG SG 550",
    "okv0o.json" to "M16A2",
    "okv7o.json" to "AN-94 Abakan",
    "p6r26.json" to "FN F2000",
    "rw27g.json" to "Rapier",
    "rwrng.json" to "AN-94M Abakan",
    "vj2zd.json" to "DSA-58",
    "vjr1n.json" to "AK-74М",
    "wjo4p.json" to "A-545",
    "wjogp.json" to "SIG SG 550",
    "y32lo.json" to "FN SCAR-L",
    "y375z.json" to "AS Val",
    "zz7j2.json" to "HK G36C",
    "zz7y2.json" to "M4A1"
)

val weaponDeviceInventory = mapOf(
    "1gmg.json" to "Buryat Short Range Detector",
    "5wd1.json" to "SN-2 Leg",
    "9j0l.json" to "Candle Short Range Detector",
    "gd06.json" to "SN-1 Pancake",
    "gdj6.json" to "Elbrus Short Range Detector",
    "yw7k.json" to "SN-2u Leglet",
    "z47y.json" to "SN-1u Mini-Pancake"
)

val heavyInventory = mapOf(
    "4q12o.json" to "Coldcutter",
    "4qnyn.json" to "PTRD-M",
    "wj6m3.json" to "Tinderbox",
    "zzlvm.json" to "Flamethrower"
)

val machineGunInventory = mapOf(
    "1rdnq.json" to "DP",
    "4q0rl.json" to "Worn PKP",
    "5lnq4.json" to "MG 42",
    "g405g.json" to "RPK-74",
    "g407g.json" to "L86A1",
    "knl43.json" to "Worn L86A1",
    "wj7nd.json" to "RPL-20",
    "zz2g9.json" to "PKP Pecheneg",
    "zz7m9.json" to "RPD"
)

val meleeInventory = mapOf(
    "0rqqk.json" to "UVSR",
    "1rj7r.json" to "Object 6x4",
    "1rjjr.json" to "Old Sickle",
    "1rjvr.json" to "Gladius",
    "2olnv.json" to "Nail Bat",
    "4q1nj.json" to "Kurkri",
    "5lggo.json" to "Fire Razor",
    "5lgno.json" to "Glock Feldmesser 78",
    "5lgvo.json" to "Shinobigatana",
    "6wz1n.json" to "Fluorite",
    "6wz6n.json" to "Survival SP8 Ontario Machete",
    "6wzzn.json" to "Corrosive Saw",
    "7l5g9.json" to "Endgame",
    "7l5n9.json" to "Cleaver",
    "96w5q.json" to "Grabber",
    "96w9q.json" to "Hunter’s Knife",
    "dmvog.json" to "Ka-Bar BKR3 Tactical Knife",
    "g4vmn.json" to "Crowbar",
    "j5vvl.json" to "Military Stalkers’ Cleaver",
    "knvvj.json" to "Icy Kurkri",
    "knvwj.json" to "Antiterror",
    "lyv22.json" to "Hunter’s Machete",
    "m0v5k.json" to "Bone Knife",
    "m0vmk.json" to "Hatchet",
    "m0vvk.json" to "NR-43",
    "n42y9.json" to "Steel Tiger Karambit",
    "ok995.json" to "Diversion Knife",
    "ok9m5.json" to "Hammer",
    "ok9w5.json" to "Misericorde",
    "p613d.json" to "M9 Bayonet",
    "p614d.json" to "Katran-1 Combat Knife",
    "qjg24.json" to "Sapper’s Shovel",
    "qjgg4.json" to "Frozen Ice Pick",
    "qjgr4.json" to "Slavs Battle axe",
    "rwzqz.json" to "Ritual Hatchet",
    "rwzzz.json" to "6x9 Knife",
    "vj497.json" to "Cossack Shashka",
    "wj66z.json" to "Cauterizer",
    "wj67z.json" to "КО-1",
    "y3jj0.json" to "Acid Razor",
    "y3jp0.json" to "Sledgehammer",
    "zzl2k.json" to "OTs-04",
    "zzllk.json" to "Razor"
)

val pistolInventory = mapOf(
    "1r77r.json" to "Fort-12",
    "1r7dr.json" to "PM",
    "1rj9g.json" to "Eternal Novice’s PM",
    "4qn6j.json" to "OTs-33 Pernach",
    "5ln9o.json" to "Glock 17",
    "5lngo.json" to "Mauser C96",
    "969mq.json" to "PB",
    "dmjog.json" to "Cobra Two-Tone",
    "g4m0n.json" to "TT",
    "g4mmn.json" to "Walther P99",
    "g4mvn.json" to "Beretta 92FS",
    "g4vk6.json" to "Dream",
    "j5ovl.json" to "Worn Colt Python",
    "knmgj.json" to "Colt Python",
    "ly2v2.json" to "Desert Eagle Mark VII",
    "ly2z2.json" to "RSh-12",
    "m0m5k.json" to "Sig Sauer P320",
    "n4m93.json" to "МР-412",
    "rwzmv.json" to "Bee",
    "wj71z.json" to "SR-1 Gyurza",
    "y32j0.json" to "Beretta 93R",
    "y32po.json" to "Ingram MAC-10",
    "y32z0.json" to "Desert Eagle Mark XIX",
    "zz22k.json" to "R-92",
    "zz25k.json" to "SW1911",
    "zz2lk.json" to "Browning Hi-Power",
    "zz2pn.json" to "PMM"
)

val shotgunInventory = mapOf(
    "1r742.json" to "BM-16",
    "4qn2o.json" to "Protecta",
    "5ln0q.json" to "Shorty 590",
    "5ln7q.json" to "Saiga-12K",
    "6w64y.json" to "Grizzly 8.5",
    "969ky.json" to "BM-16 Sawed-Off",
    "g4mz5.json" to "TOZ-34",
    "j5o9g.json" to "OTs-62",
    "m0mz2.json" to "M1014 Breacher",
    "rw2ky.json" to "MTs255",
    "wj7v3.json" to "RMB-93",
    "y32o3.json" to "МР-153",
    "y32v3.json" to "МР-133",
    "zz29n.json" to "Cobray Terminator",
    "zz2nm.json" to "Mossberg 590A1",
    "zz2vm.json" to "Franchi SPAS-12"
)

val sniperInventory = mapOf(
    "1r79g.json" to "SКТ-40",
    "1r7rg.json" to "Mosin’s Carbine",
    "4qn7r.json" to "CR-380",
    "4qnkr.json" to "Steyr Scout",
    "4qnor.json" to "Worn SVD",
    "5ln51.json" to "Worn SVT-40",
    "5lno1.json" to "SVU",
    "5lnp0.json" to "SOK-94",
    "5lny1.json" to "M40A5",
    "7lnk7.json" to "MTs-116M",
    "9696l.json" to "Worn SKS",
    "g4m2p.json" to "Mosin’s Rifle",
    "g4m46.json" to "SKS",
    "g4mn6.json" to "Winchester M70",
    "j5oq0.json" to "FG-42 Whip",
    "knm5y.json" to "Worn M1A",
    "knmdv.json" to "Gauss Rifle",
    "knmpy.json" to "VSS Vintorez",
    "ly29k.json" to "Worn L96A1",
    "qj23j.json" to "MTs-558",
    "rw23l.json" to "Avalanche",
    "rw26v.json" to "Karbach OTL-03",
    "rw2d5.json" to "McMillan CS5",
    "wj72d.json" to "АВТ-40",
    "wj732.json" to "SVT-40",
    "wj792.json" to "Alpine TPG-1",
    "wj7l2.json" to "L96A1",
    "y32gk.json" to "Worn M40A5",
    "y32nk.json" to "WA2000",
    "zz23y.json" to "Worn Winchester M70",
    "zz2ky.json" to "VSS-M \\\"Vintorez\\\"",
    "zz2wy.json" to "M1A FA"
)

val submachineInventory = mapOf(
    "1r756.json" to "Viper",
    "1r7v1.json" to "IMI Mini Uzi",
    "1rdg6.json" to "HK MP5",
    "2od90.json" to "Scorpion EVO III",
    "3gr1z.json" to "SIG MPX",
    "4q0lp.json" to "PP-2000",
    "5ldrg.json" to "FN P90",
    "5lnv0.json" to "HK MP5K",
    "969r0.json" to "Tsunami",
    "969vz.json" to "HK UMP9",
    "96mj0.json" to "PP-91 KEDR",
    "g40d0.json" to "IMI Uzi",
    "knlq0.json" to "SR-2M Veresk",
    "m0m7j.json" to "SMG Nut",
    "qjvo6.json" to "Spectre M4",
    "y37dz.json" to "PP-19-01 Vityaz",
    "y37qz.json" to "TDI KRISS Vector",
    "zz742.json" to "AEK-919K Kashtan",
    "zz7d2.json" to "PP-19 Bizon-2-01"
)



val armorInventory = mapOf(
    "clothes" to "Clothes",
    "combat" to "Combat",
    "combined" to "Combined",
    "device" to "Device",
    "scientist" to "Scientist"
)

val clothesInventory = mapOf(
    "g4yw6.json" to "Bandit Leather Jacket",
    "1rk6g.json" to "Bandit Jacket",
    "5lr71.json" to "Leather Jacket",
    "96n2l.json" to "Jacket",
    "y35ok.json" to "Mole Suit",
    "zzy6y.json" to "Mole Bandit Jacket"
)

val combatInventory = mapOf(
    "0rn7d.json" to "Vanguard Armored Suit",
    "1rpl6.json" to "Granite Super-Heavy Armored Suit",
    "2oqdl.json" to "Fleece Protective Suit",
    "2oqll.json" to "Jaeger Exoarmor",
    "3g6nl.json" to "Currant Ghillie Suit",
    "3g6rl.json" to "Hoplite Armored Suit",
    "4q9op.json" to "Worn Beast Slayer",
    "4ql0r.json" to "Cloak",
    "4ql1r.json" to "Centurion Armored Exoskeleton",
    "4ql2r.json" to "Jacket with Body Armor",
    "4qlvo.json" to "Worn Centurion",
    "5lr4q.json" to "Yorsh Protective Armored Suit",
    "5lrn1.json" to "Voshod Heavy Armored Suit",
    "5lrvq.json" to "Damaged Jaeger",
    "6w06p.json" to "Scout Suit",
    "6w0rp.json" to "Worn Trapper Suit",
    "6w0zp.json" to "Trump Exoskeleton",
    "7lm56.json" to "Exoskeleton",
    "7lmn6.json" to "Houndmaster Protective Suit",
    "7lmr6.json" to "Trapper Suit",
    "96n5l.json" to "Worn Legionnaire",
    "96n5y.json" to "Worn Trump",
    "96n9l.json" to "Striker Armored Suit",
    "96yz0.json" to "Reiter Super-Heavy Armored Suit",
    "dmgjj.json" to "Healing Berill",
    "dmgqj.json" to "Hunter’s Cloak",
    "dmgvj.json" to "Osh Protective Suit",
    "dmgw2.json" to "Ghillie Suit",
    "g4310.json" to "Chieftain Super-Heavy Armored Suit",
    "g43k0.json" to "Mule Exoskeleton",
    "g4y06.json" to "Worn Striker Armored Suit",
    "g4y3n.json" to "CD-1 Jumpsuit",
    "g4yq5.json" to "Grenadier Exoskeleton",
    "j5krg.json" to "Phantom Hunter Armored Suit",
    "kn360.json" to "Worn Mule",
    "knq0p.json" to "Lynx Armored Suit",
    "knqly.json" to "Reporter’s Armor",
    "knqmy.json" to "Bandit Cloak",
    "ly3kj.json" to "Apostle Super-Heavy Armored Suit",
    "m062y.json" to "Jacket with Body Armor",
    "m065y.json" to "Worn Voshod Heavy Armored Suit",
    "n4ry1.json" to "Worn Osh Protective Suit",
    "ok0w6.json" to "Worn Thug Heavy Armored Suit",
    "p6m3w.json" to "Berill-5M Armored Suit",
    "p6mg4.json" to "Ratcatcher Exoarmor",
    "p6mrw.json" to "Worn Fleece Protective Suit",
    "qj1y6.json" to "Worn Ace",
    "qjoz3.json" to "Bear Exoskeleton",
    "vj12r.json" to "Worm Armored Suit",
    "vj1rr.json" to "Worn Hoplite Armored Suit",
    "wj49p.json" to "Beast Slayer Exoarmor",
    "wjg62.json" to "Legionnaire Heavy Armored Suit",
    "wjgp3.json" to "Damaged Centurion",
    "y352k.json" to "Thug Heavy Armored Suit",
    "y35p3.json" to "Worn Jaeger",
    "zzjk2.json" to "Ace Exoskeleton",
    "zzy5y.json" to "Worn Exoskeleton",
    "zzy9m.json" to "Aborigine Exoskeleton",
    "zzyjk.json" to "CD-2 Armored Suit"
)

val combinedInventory = mapOf(
    "0r429.json" to "Bandit Suit",
    "0r4gy.json" to "Expedition Suit",
    "0r4k9.json" to "Worn AH-3 Seeker Suit",
    "1rk7g.json" to "PS-1 Picklock",
    "1rkdg.json" to "Damaged AH-2 Nomad",
    "1rkq2.json" to "Worn SKAT-9m",
    "1rkqg.json" to "Worn PSZ-10",
    "1rkz2.json" to "Brigand Armored Suit",
    "2oqnl.json" to "AH-1 Drifter Suit",
    "3g69l.json" to "SKAT-9b Armored Suit",
    "5l1yg.json" to "RAPS AH-6 Nomad",
    "5lrg1.json" to "Kingpin Armored Suit",
    "96nml.json" to "Worn AH-2 Nomad",
    "dmg02.json" to "Worn Kleptomaniac",
    "g4yo5.json" to "Damaged SKAT-9m",
    "g4yo6.json" to "Worn Kingpin",
    "j5ko0.json" to "Zarya Jumpsuit with Gas Mas",
    "j5kv0.json" to "AH-2 Nomad Suit",
    "knqvy.json" to "Falcon Armored Suit",
    "lyjvk.json" to "AH-3 Seeker Suit",
    "m034j.json" to "Punisher Armored Suit",
    "m06k2.json" to "SKAT-10 Armored Suit",
    "m06my.json" to "Bandit Suit with Gas Mask",
    "n4rm1.json" to "Kleptomaniac Suit",
    "n4rp1.json" to "Worn Mockingbird Armored Suit",
    "ok0jm.json" to "Worn SKAT-9b",
    "ok0v6.json" to "Worn Falcon Armored Suit",
    "p6m1w.json" to "RAPS AH-4 Raider",
    "p6m4w.json" to "Worn AH-4 Raider",
    "qjo2j.json" to "Zarya Jumpsuit",
    "qjogj.json" to "Mockingbird Armored Suit",
    "rwgmg.json" to "Hounds Exoskeleton",
    "rwn2v.json" to "Tourist Jumpsuit",
    "rwnqv.json" to "Damaged AH-3 Seeker Suit",
    "rwnrv.json" to "Gorka-3 Suit",
    "vj14r.json" to "RAPS AH-5 Pilgrim",
    "vj1pp.json" to "Worn Tourist",
    "y35jk.json" to "SKAT-9m Armored Suit",
    "y35l3.json" to "RAPS Spanner",
    "y3qgz.json" to "Worn AH-6 Nomad",
    "zzy5m.json" to "Worn AH-5 Pilgrim",
    "zzyly.json" to "PSZ-10 Armored Suit"
)

val scientistInventory = mapOf(
    "0r4q9.json" to "MIS-113 Iolite",
    "2ovr0.json" to "Saturn Jumpsuit",
    "3gdoz.json" to "Worn Saturn Jumpsuit",
    "4qlnr.json" to "MIS-99 Malachite",
    "7lzw3.json" to "Damaged Saturn Jumpsuit",
    "96ngz.json" to "Improved Hazmat Suit",
    "g4ym6.json" to "SEVA Jumpsuit",
    "j5k10.json" to "Worn SEVA Jumpsuit",
    "j5k6g.json" to "Worn Emerald",
    "knqgy.json" to "Worn MIS-99 Amber",
    "knqwp.json" to "Worn Topaz",
    "lyj2k.json" to "Zarya-B Jumpsuit",
    "lyjzk.json" to "Worn REAPER Jumpsuit",
    "m06vy.json" to "MIS-116 Emerald",
    "n4r21.json" to "MIS-X ATLAS",
    "ok096.json" to "MIS-122 Amethyst",
    "ok0m6.json" to "Bandit Suit with Gas Tanks",
    "qjokj.json" to "Worn MIS-99M Malachite",
    "qjor3.json" to "Worn Iolite",
    "rwnzv.json" to "MIS-105 Topaz",
    "wj4lp.json" to "Peresvet Jumpsuit",
    "wjg72.json" to "MIS-99 Amber",
    "wjgm2.json" to "Raincoat",
    "wjgo2.json" to "IP-4M",
    "zzy2y.json" to "REAPER Jumpsuit"
)

val armorDeviceInventory = mapOf(
    "1rp4q.json" to "Night-Vision Goggles",
    "5l134.json" to "NVD-11 Export",
    "96y1w.json" to "Home-made NVG",
    "g43pg.json" to "2nd Generation NVG",
    "y3qyw.json" to "NVG O1M"
)

val attachmentInventory = mapOf(
    "barrel" to "Barrel",
    "collimator_sights" to "Collimator sights",
    "forend" to "Forend",
    "mag" to "Magazine",
    "other" to "Other",
    "pistol_handle" to "Pistol handle"
)

val artefactInventory = mapOf(
    "biochemical" to "Biochemical",
    "electrophysical" to "Electrophysical",
    "gravity" to "Gravity",
    "thermal" to "Thermal",
)

val bioArtefactInventory = mapOf(
    "1kdg.json" to "Crystal Thorn",
    "4lml.json" to "Firefly",
    "5r04.json" to "Slime",
    "5rd1.json" to "Steel Kolobok",
    "9nml.json" to "Thorn",
    "gy06.json" to "Urchin",
    "gyjg.json" to "Acid Crystal",
    "jkj4.json" to "Pellicle",
    "kqj3.json" to "Snail",
    "ljpq.json" to "Polyhedron",
    "qo59.json" to "Bubble",
    "wgvd.json" to "Mica",
    "y5vw.json" to "Slug",
    "zy7y.json" to "Kolobok",
    "zyv9.json" to "Lollipop"
)

val electroArtefactInventory = mapOf(
    "1k96.json" to "Sparkler",
    "4lkp.json" to "Moonlight",
    "5r5g.json" to "Snowflake",
    "5rwq.json" to "Shard",
    "9nd0.json" to "Electro Crysta",
    "gyn0.json" to "Flare",
    "gyq5.json" to "Spiral",
    "kqr0.json" to "Helium",
    "qo06.json" to "Transformer",
    "wg3p.json" to "Disintegrator",
    "wg53.json" to "Atom",
    "y54z.json" to "Shell",
    "y5w3.json" to "Prism",
    "zy32.json" to "Battery",
    "zyrm.json" to "Mirror"
)

val gravityArtefactInventory = mapOf(
    "1k4q.json" to "Meat Chunk",
    "1kv2.json" to "Gravi",
    "4l1r.json" to "Proto-Jellyfish",
    "5r34.json" to "Soul",
    "5rg1.json" to "Dark Jellyfish",
    "5rpq.json" to "Amberite",
    "9n1w.json" to "Stone Blood",
    "9nvy.json" to "Quirk",
    "gyg5.json" to "Goldfish",
    "gypg.json" to "Stone Bile",
    "gyv6.json" to "Stone Flower",
    "kqgy.json" to "Bracelet",
    "wg62.json" to "Night Star",
    "wgr3.json" to "Black Crystal",
    "wgzd.json" to "Frame",
    "y5jk.json" to "Veiner",
    "y5m3.json" to "Cryogen",
    "y5yw.json" to "Spring",
    "zyly.json" to "Jellyfish",
    "zyo9.json" to "Swamp Rot",
    "zypm.json" to "Gold Gravi"
)

val thermalArtefactInventory = mapOf(
    "4l7p.json" to "Eye",
    "4lgj.json" to "Razor",
    "5rog.json" to "Droplet",
    "5rzo.json" to "Crust",
    "gy10.json" to "Crystal",
    "gyln.json" to "Frost",
    "jkml.json" to "Eye of the Storm",
    "kqoj.json" to "Heel",
    "kqp0.json" to "Flame",
    "ljrj.json" to "Radiator",
    "qo94.json" to "Chicken God",
    "qoq6.json" to "Sun",
    "wglp.json" to "Mama’s Beads",
    "wgwz.json" to "Fahrenheit",
    "y5k0.json" to "Whirlwind",
    "y5nz.json" to "Wolf Tears",
    "zyqk.json" to "Leaded Glass",
    "zyw2.json" to "Fireball"
)

val backpackInventory = mapOf(
    "1rwg2.json" to "Mobile Camp"
)

val containerInventory = mapOf(
    "0ndk.json" to "Jagdtasche",
    "12r1.json" to "MBSS Backpack",
    "2vvv.json" to "KZS-3",
    "49gj.json" to "KZS-4",
    "7yl7.json" to "Errand Junior Backpack",
    "9yyq.json" to "KZS-1 Container",
    "g35n.json" to "Bear’s Den — 6 Container",
    "g3ln.json" to "Fridge Container",
    "j33l.json" to "KZS-2",
    "jmp6.json" to "Transformer Bag",
    "k3oj.json" to "Cocoon Container",
    "l332.json" to "Hellboy Backpack",
    "lny1.json" to "Tri-Zip Assault Backpack",
    "m3pk.json" to "Freezer Container",
    "n3v9.json" to "KZS-5",
    "nv43.json" to "NPA Backpack",
    "odq0.json" to "Sports Bag",
    "p92d.json" to "Hive Container",
    "p99d.json" to "IU-2 Container",
    "q194.json" to "Forager Container",
    "w4wz.json" to "Bear’s Den — 4 Container",
    "yqq0.json" to "KZS-1u Container",
    "zjqk.json" to "Marathon bag"
)

val grenadeInventory = mapOf(
    "12dq.json" to "M381 Grenade Round",
    "29dm.json" to "F-1",
    "31rk.json" to "M67",
    "65r6.json" to "VOG-25 Grenade Round",
    "7ynr.json" to "M2 Grenade Round",
    "7yrr.json" to "V40 Mini-Grenade",
    "94mw.json" to "VOG-25 Podkidysh Grenade Round",
    "dkq9.json" to "RGD-5",
    "gl0g.json" to "M397 Grenade Round",
    "jm94.json" to "RGN",
    "lngq.json" to "RGO",
    "nvpw.json" to "Flare Grenade",
    "p2r5.json" to "M84",
    "vyrg.json" to "M84 QD"
)

val miscInventory = mapOf(
    "006ry.json" to "Scorpion EVO III Part #2",
    "19yr2.json" to "Lantac BMD Part #3",
    "21w15.json" to "Sledgehammer Part #2",
    "21wo5.json" to "VIKING Tactics Part #1",
    "34245.json" to "Sledgehammer Part #3",
    "342g5.json" to "VIKING Tactics Part #2",
    "4kjko.json" to "Magazine P320 Part #3",
    "55j5q.json" to "SCORPION DRUM Part #3",
    "6ojw0.json" to "Lantac BMD Part #1",
    "77d7j.json" to "Sledgehammer Part #4",
    "77dlj.json" to "VIKING Tactics Part #3",
    "9do6y.json" to "Lantac BMD Part #2",
    "dr9m2.json" to "Sig Sauer P320 Part #4",
    "dr9r2.json" to "Sledgehammer Part #1",
    "gnz45.json" to "SCORPION DRUM Part #1",
    "j0w0g.json" to "Lantac Dragon Part #3",
    "j0w5g.json" to "AM-17 Part #3",
    "kr2np.json" to "AM-17 Part #1",
    "kr2rp.json" to "Lantac Dragon Part #1",
    "l0oyo.json" to "AM-17 Part #4",
    "lyr3k.json" to "Strange Crate",
    "mrn02.json" to "Scorpion EVO III Part #3",
    "nko42.json" to "Sig Sauer P320 Part #1",
    "ol6km.json" to "Scorpion EVO III Part #4",
    "p6qz2.json" to "Black Regalia",
    "pjo64.json" to "Sig Sauer P320 Part #2",
    "q0p03.json" to "Lantac Dragon Part #2",
    "q0pj3.json" to "AM-17 Part #2",
    "rj9wy.json" to "Scorpion EVO III Part #1",
    "vn5jp.json" to "Sig Sauer P320 Part #3",
    "w3y33.json" to "Magazine P320 Part #2",
    "y4643.json" to "Magazine P320 Part #1",
    "z3nzm.json" to "SCORPION DRUM Part #2"
)
